name: Build Image

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Build image
      run: gradle bootBuildImage --imageName ghcr.io/${{ github.repository }}
    
    - name: Tag image
      run: >-
        docker tag ghcr.io/${{ github.repository }}:latest
        ghcr.io/${{ github.repository }}:${{ github.run_number }}
    - name: Docker Login
      uses: docker/login-action@v1.8.0
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GH_ACCESS_TOKEN }}

    - name: Push Docker image
      if: ${{ github.event_name != 'pull_request' }}
      run: >-
        docker push ghcr.io/${{ github.repository }}:latest &&
        docker push ghcr.io/${{ github.repository }}:${{ github.run_number }}
